### ISSUE TITLE
v1.032 tag missing

### ISSUE THREAD

**Issue by KarolisM** [Infinidat/slimfastq#1]
Hi,

I missed one of your tags which was available since recently: v1.032.
Is there some reason why you removed this?

Thanks,
Karolis

**Comment by sgdb** [comment]
Hi Karolis,

I removed this tag by accident and couldn't find a way to restore it.

Best,
Josef

**Comment by jjezra** [comment]
Hi Karolis, 
I've retrieved v1.032. Note that this version is slower that the recent one, and does not support PacBio long lines. 

Best, 
Josef

**Comment by KarolisM** [comment]
Thank you, I will that in mind.

Best,
Karolis
