### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ckin77** [Infinidat/slimfastq#2]
Hello, 

When trying to compile version slimfastq-2.03, the following error is received.
How do I resolve these errors?

g++ -Wall -Werror  -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -msse3 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -o slimfastq bfiler.cpp config.cpp filer.cpp gens.cpp main.cpp qlts.cpp recs.cpp usrs.cpp xfile.cpp
gens.cpp:165:10: error: unknown type name 'uint'; did you mean 'int'?
    for (uint i = 0; i < llen; i++) {
         ^~~~
         int
gens.cpp:251:10: error: unknown type name 'uint'; did you mean 'int'?
    for (uint i = 0; i < llen; i++) {
         ^~~~
         int
2 errors generated.
make: *** [slimfastq] Error 1

Thanks

**Comment by jjezra** [comment]
Hi Ckin, 

I've pushed (what I hope to be) a fix. Would you be able to try again with the recent master?

Thanks, 
jezra

**Comment by ckin77** [comment]
Hi Jezra,

Apologies for my slow response.
I’ve downloaded v2.03 and continue to receive the following error.
Perhaps it’s an error on my part?


ck$ make

g++ -Wall -Werror  -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -msse3 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -o slimfastq bfiler.cpp config.cpp filer.cpp gens.cpp main.cpp qlts.cpp recs.cpp usrs.cpp xfile.cpp

gens.cpp:165:10: error: unknown type name 'uint'; did you mean 'int'?

    for (uint i = 0; i < llen; i++) {

         ^~~~

         int

gens.cpp:251:10: error: unknown type name 'uint'; did you mean 'int'?

    for (uint i = 0; i < llen; i++) {

         ^~~~

         int

2 errors generated.

make: *** [slimfastq] Error 1

Thanks,
Cris


From: Cristine Kinross <cristine.kinross@gmail.com>
Date: Friday, September 11, 2020 at 11:41 AM
To: "Kinross, Cris" <cris.kinross@thermofisher.com>
Subject: Fwd: [Infinidat/slimfastq] make error (#2)

CAUTION: This email originated from outside of Thermo Fisher Scientific. If you believe it to be suspicious, report using the Report Phish button in Outlook or send to SOC@thermofisher.com.




Begin forwarded message:

**Comment by jjezra** [comment]
Hi Ckin77, 

The fix is not in v2.03 (or v2.04) as I was waiting to your fix confirmation. Would you be able to download the most recent dev code and try? 
One way to do it is in downloading the zip file from https://github.com/Infinidat/slimfastq/archive/master.zip

Thank you!

**Comment by ckin77** [comment]
Hi Josef,

That worked but the following error occurs when I sudo make install.

install -t /usr/local/bin/ ./slimfastq tools/slimfastq.multi

install: illegal option -- t

usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]

               [-o owner] file1 file2

       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]

               [-o owner] file1 ... fileN directory

       install -d [-v] [-g group] [-m mode] [-o owner] directory ...

make: *** [install] Error 64


How do I avoid that error?


Thanks,

Cris

**Comment by jjezra** [comment]
Hi Cris, 
I can see now that some versions of install do not support the "-t" option. I'll fix that in 2.04. In the meantime, please simply use "sudo cp ./slimfastq ./tools/slimfastq.multi /usr/local/bin/"
Best,

**Comment by ckin77** [comment]
Hi Josef,

It works great, thank you.
This is really helpful.

Regards,
Cris
